openapi: 3.1.0
info:
  title: Financial Report Generator API
  version: 1.0.0
  description: 기업명을 받아 재무제표 파일을 생성하고 다운로드 링크를 반환합니다.
servers:
  - url: https://github.com/minconomy88/dart-corp-codes/blob/main/corp_codes_all.json
paths:
  /generate-report:
    get:
      operationId: generateFinancialReport
      summary: 기업 재무제표 통합 파일 생성
      parameters:
        - name: corp_name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 생성된 재무제표 파일 링크
          content:
            application/json:
              schema:
                type: object
                properties:
                  download_url:
                    type: string
                    format: uri
        '404':
          description: 기업명을 찾을 수 없음 또는 파일 생성 실패
