openapi: 3.1.0
info:
  title: Financial Report API
  version: 1.1.0
  description: |
    기업명을 입력하면 DART 공시 API를 통해 재무제표 데이터를 받아와
    Excel 파일을 생성하고 다운로드 링크를 제공합니다.

servers:
  - url: https://flask-financial-report.onrender.com
    description: Render 배포된 Flask API 서버

paths:
  /generate-report:
    get:
      operationId: generateFinancialReport
      summary: 기업 재무제표 엑셀 다운로드 링크 생성
      description: |
        DART API를 사용하여 실시간 재무제표 데이터를 받아 엑셀 파일로 생성한 후 다운로드 링크를 제공합니다.
      parameters:
        - name: corp_name
          in: query
          required: true
          description: 조회할 기업명 (예: 삼성전자)
          schema:
            type: string
        - name: bsns_year
          in: query
          required: false
          description: 사업연도 (기본값: 2023)
          schema:
            type: string
        - name: reprt_code
          in: query
          required: false
          description: 보고서 구분 코드 (예: 11011은 사업보고서, 기본값: 11011)
          schema:
            type: string
      responses:
        '200':
          description: 다운로드 가능한 Excel 파일 링크
          content:
            application/json:
              schema:
                type: object
                properties:
                  corp_name:
                    type: string
                  corp_code:
                    type: string
                  bsns_year:
                    type: string
                  download_url:
                    type: string
        '400':
          description: corp_name 누락 시 오류
        '404':
          description: 기업명을 찾을 수 없거나 DART에서 데이터 없음
        '500':
          description: 서버 오류 또는 외부 JSON 불러오기 실패

